[package]
name = "viuwa"
version = "0.0.44"
edition = "2021"
authors = ["Lance Warden"]
description = "Yet another \"super simple\" cli/tui ANSI image viewer, targeting compatibility with wasm32-wasi."
license = "MIT OR Apache-2.0"
repository = "https://github.com/WanderLanz/Viuwa"
keywords = ["image-viewer", "ansi", "cli", "tui"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.0.*", features = ["derive", "env"] }
image = "0.24.*"
# base64 = { version = "0.13.*", optional = true }

[target.'cfg(any(unix,windows))'.dependencies]
crossterm = "0.25.*"

# [features]
# sixel = []
# iterm = ["dep:base64"]
