### Example configuration for viuwa
# Any key defined in the configuration file can be overridden by
# its corresponding environment variable or command line argument.
# None of the keys are required, but the configuration file must be valid TOML.


# Silence warnings and messages
# true or false (default: false)
quiet = false

# Filter for resizing the image
# "nearest" (default), "box", "triangle", "hamming", "catmull", "mitchell",
#   "gaussian" (unavailable with "fir" feature enabled), or "lanczos"
filter = "hamming"

# ANSI color mode for displaying images
# "truecolor" (default), "gray", "256", or "256gray"
color = "256gray"

# Luma correction exclusively for "256" color mode
# 0 to 100 (default: 100)
luma_correct = 0

# Display the ANSI image inline (don't open alternate screen)
# true or false (default: false)
inline = false

# Maximum width (in character units) of an inlined image
# 1 to max columns (default: max columns)
width = 100

# Maximum height (in character units) of an inlined image
# 1 to max rows (default: max rows)
height = 100
